- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message Error
      debug:
        msg: "Hello World!"
      failed_when: true
      ignore_errors: true
    - name: Hello Message
      debug:
        msg: "Hello World!"

